### ISSUE TITLE
FB2:S24:UI:Works: search results' display

### ISSUE THREAD

**Issue by RK206** [culturesofknowledge/emlo-project#509]
**Works: search results' display**

In this search in Works on 'Origin or destination', with the term 'contains: Hall' these are the two screens at 90% (Figs 1 and 2) on a large screen. You have to reduce to 33% view in EMLO-edit-new to see what's where, and then  
       you can't read the text (Fig. 3).

<img width="1026" height="487" alt="Image" src="https://github.com/user-attachments/assets/cdcd4314-6afe-413b-b210-e6380ecdc54d" />

Issue Reference: Slide 24 in EMLOedit_Feedback2_2025.10.28.pptx

**Comment by RK206** [comment]
Fixed the issue for better visibility of the table

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan This looks much better, thanks. But I just spotted a couple of examples where the URL spills over the side of the column, ID 957678 and ID 999865. You can see quite a few examples if you search Editors notes contains 'http'

**Comment by RK206** [comment]
This has been fixed as part of github.com/culturesofknowledge/emlo-project/issues/533 changes. Please verify if it looks good after changes

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan In Safari I still have a problem with the URL spilling out of the column (search editors notes http). It's fine in Chrome.

**Comment by RK206** [comment]
Implemented fixes for Safari. I have tested my best and seems to be working fine.
Please test from your side when ready for test after deployment

**Comment by RK206** [comment]
Deployed. Ready to test

**Comment by MillieG711** [comment]
@RK206 Looks good, thanks, closed the issue.
