### ISSUE TITLE
FB3:S8:BE:Works search results

### ISSUE THREAD

**Issue by RK206** [culturesofknowledge/emlo-project#525]
**Works search results**

The date that shows up in the '**Date for ordering**' column should be the green date, not the red date.

<img width="1133" height="441" alt="Image" src="https://github.com/user-attachments/assets/58df778e-3f7b-4f18-a014-6ee8a0f815f6" />

Issue Reference: Slide 8 in EMLOedit_Feedback3_2025.11.12.pptx

**Comment by RK206** [comment]
Fixed issue to ensure consistent display of date values.

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan I think there's been a misunderstanding here. I meant that the green date instead of the red date should be visible in the 'date for ordering' column in the results, which it now is (see issue #524). But the red date should still appear within the letter record. The date range in the 'From' and 'To' box is the actual date of the letter which has been entered, and which shows up in the front end, whereas the date for ordering is assigned only in the back-end. And if there is a date range, the date for ordering is taken from the date in the 'To' box.

So, the picture above should not change. It's just that the green date should show in the date for ordering column in the results list (as it now does).

As an example, you can look at Work ID 1050353. This letter has been given a date range of 1 Jan 1487 to 31 Dec 1487. Therefore, the date for ordering is 31.12.1487. If you search for this ID in Compact search, you'll see that the Description says 1 Jan 1487 to 31 Dec 1487, and the Date for ordering says 1487-12-31, which is correct. But if you go into the letter record, the 'From' and 'To' boxes now say From 31 Dec 1487 To 31 Dec 1487. It should be From 1 Jan 1487 To 31 Dec 1487, with the date for ordering below.

**Comment by RK206** [comment]
Fixed the issue. Please verify.

**Comment by MillieG711** [comment]
@anusharanganathan @RK206 This is not fixed as the wrong date is still showing in the first date box. Would it be helpful to discuss it in the meeting tomorrow?

**Comment by RK206** [comment]
Deployed the code now. It should work now.

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan thanks, closed the issue
