### ISSUE TITLE
FB3:S13:BE:People search results flourished

### ISSUE THREAD

**Issue by RK206** [culturesofknowledge/emlo-project#530]
**People: search results: flourished**

Search fl. 1664-1665. Old brings up all people whose floruit overlaps with that range. New only brings up people whose whole fl. range is within that range, i.e. both years must be within that range. It should also bring up results for whom only one of the years is within that range, and where the given range falls within that person's fl.

E.g. Search
**Names and titles/roles contains "Maffei"
Flourished between 1664 and 1665.**
Old brings up 'Maffei, Raffaello, fl. 1661-1668' (ID 902596); new brings up no results.

New also doesn't bring up people whose fl. is a single year within the given range.

E.g. Search:
**Names and titles/roles contains "Addenbrooke".
Flourished between 1706 and 1717**. 
Old brings up 'Addenbrooke, Samuel, fl. 1716' (ID 925094), but new does not. The only way to bring him up in new is to put 1716 as the first year in the range, and leave the second year blank. I.e. 1716-1716 doesn't work either.

NB. The first search also brings up three results which have an incorrect floruit, i.e. the second date is before the first date, and which do not appear in old. We will correct these as they are mistakes. However, we are confused as to why they are coming up in a search for **Flourished between 1664 and 1665:**

Nodari, Santi, fl. 1800 to 1616 (ID 911478)
Palthenius, Zacharias, fl. 1694 to 1616 (ID 910825)
Whalley, Thomas, fl. 1690 to 1621 (ID 10525)

Issue Reference: Slide 13 in EMLOedit_Feedback3_2025.11.12.pptx

**Comment by RK206** [comment]
Fixed the issue to pull records properly.
I see it pulling records which or before, or after For example with ID 428, 937370. Please verify and let me know that is what expected.

**Comment by RK206** [comment]
Realized that it is working as expected as mentioned in the issue https://github.com/culturesofknowledge/emlo-project/issues/531

**Comment by MillieG711** [comment]
@anusharanganathan @RK206 Actually the first part of this is not fixed. See the example given above for Maffei (ID 902596). The search is Maffei, f. 1664-1665. His fl. is 1661-1668, and therefore he should come up, because we know that he definitely was active between 1664 and 1665. The rest of this issue is fixed.

**Comment by RK206** [comment]
@MillieG711 It looks like there no flourished date for the record 902596. Probably in EMLO old the date has been provided but not in new or am I missing something? Can you please verify again?

<img width="1842" height="791" alt="Image" src="https://github.com/user-attachments/assets/0aade865-c96d-4748-b89f-0c68ea0416db" />

<img width="1842" height="791" alt="Image" src="https://github.com/user-attachments/assets/2a5353a0-d329-4961-b06f-c44c5c1d3cf4" />

**Comment by MillieG711** [comment]
@RK206 I've no idea what happened to the dates! I'm sure they were there before. I added them, and the search works fine, so closed the issue.
