### ISSUE TITLE
FB3:S14:BE:People search results flourished

### ISSUE THREAD

**Issue by RK206** [culturesofknowledge/emlo-project#531]
**People: search results: flourished**

Search e.g. **fl. from 1816**. Old brings up more results than new. New is not bringing up the people whose fl. is '**xxxx or before**'. 

E.g. search 
**Names and titles/roles contains "amherst".
Flourished after 1816.**
In old this brings up one result (**Amherst, John T. (Captain), fl. 1827 or before [ID 428]**), in new no results.

Also, old brings up results where the last fl. year is after 1816, whereas in new both years must be after it. E.g. search fl. **from 1850** should bring up a record whose fl. is **1830 to 1867 (ID 937340)**, i.e. where only the second year is after 1850. New only brings up results where both years are after 1850.

Ditto, Search e.g. **fl. to 1500**. Old brings up more results than new. As above, it also doesn't bring up the records with fl. '**xxxx or after**'. 

And also, it only brings up those records where both fl. years are before 1500. It should also bring up results where only the first year is before 1500.

I.e. It should bring up records with a fl. of e.g. '**1413 or after**' (ID 907766) and '**1435 to 1866**' (ID 939020), where only the first year is before 1500.

Issue Reference: Slide 14 in EMLOedit_Feedback3_2025.11.12.pptx

**Comment by RK206** [comment]
This has been fixed with other issues. I believe it is working now as expected

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan It's working now for the issue mentioned above, thanks. But again it's a problem with the results that have open-ended ranges. So if you search Flourished after 1816, and sort by Flourished. The first 26 results (up to Selva, Anna) do not come up in old EMLO. In all those cases, it is implausible that this person would have been active after 1816, as they would be over 100 years old. So in old, the open-ended ranges only appear in the results if the given year is after 1816. Therefore, '1714 or after' does not come up, but '1827 or before' does come up. Sorry this is quite tricky!

**Comment by anusharanganathan** [comment]
> [@RK206](https://github.com/RK206) [@anusharanganathan](https://github.com/anusharanganathan) It's working now for the issue mentioned above, thanks. But again it's a problem with the results that have open-ended ranges. So if you search Flourished after 1816, and sort by Flourished. The first 26 results (up to Selva, Anna) do not come up in old EMLO. In all those cases, it is implausible that this person would have been active after 1816, as they would be over 100 years old. So in old, the open-ended ranges only appear in the results if the given year is after 1816. Therefore, '1714 or after' does not come up, but '1827 or before' does come up. Sorry this is quite tricky!

@MillieG711 should there be a time limit to how many years before or after we should search. For example someone searching for 1770, should `1816 or before` come up? In terms of writing an algorithm, this does not make sense. We should only include later dates with the word before but not earlier dates with the word after.

**Comment by MillieG711** [comment]
@anusharanganathan @RK206 It would be best if we can exclude the 'or after' and 'or before' ranges, unless the specified year is within the range that you searched for. So if you search fl. 1816 or after, that **should** bring up a record with fl. 1824 or after (or fl. 1824 or before), because 1824 is after 1816 and therefore we know that that person was active after 1816, but **not** a record with fl. 1812 or after, since 1812 is not after 1816 and therefore we don't know for certain that they were active after 1816. To your question, if someone is searching for fl. 1770 or after, then fl. 1816 or before **should** come up, because 1816 is after 1770, so we know that they were definitely active after 1770. But if you search fl. 1770 or before, then fl. 1816 or before **should not** come up, since 1816 is not before 1770, and therefore it is not definite that they were active before 1770. Even if their fl. is 1772 or before, it is still not definite that they were active before 1770 (even if it is likely), and therefore that result **should not** come up. This is how it works in old. The assumption is that if you search fl. 1770 or before, you want to get results that were definitely active before that time. It would be complicated and arbitrary to put some kind of margin in, the simplest and most helpful thing is to use the specified year.

All the rest of the fl. searches seem to be working well, so I don't want this fix to throw any of those out! There aren't many of this type of result.

**Comment by RK206** [comment]
I believe I have fixed the issue. I have tested to my best. Please check from your side.

**Comment by MillieG711** [comment]
@RK206 I am still getting the same results. Search fl. after 1816, I am seeing e.g. 910845, fl. 1610 or after. Since 1610 is not after 1816, this result should not come up.

**Comment by anusharanganathan** [comment]
@MillieG711 the changes were deployed just yesterday. It seems to work, but when you sort and go to page 5, I am not sure if the results included are correct.

**Comment by MillieG711** [comment]
@RK206 @anusharanganathan All these results look fine to me and the number of results is the same in old, so I am happy with it. Thanks, this was a tricky one!
